export default {
	"Black - Cigarette": "BASE_COMMON",
	"Black - Cracked": "BASE_COMMON",
	"Black - Default": "BASE_COMMON",
	"Black - Fangs": "BASE_COMMON",
	"Black - Gold Tooth": "BASE_COMMON",
	"Black - Lockjaw": "BASE_COMMON",
	"Black - Oooh": "BASE_COMMON",
	"Black - Open": "BASE_COMMON",
	"Black - Open-minded": "BASE_COMMON",
	"Black - Sewn": "BASE_COMMON",
	"Black - Side Open": "BASE_COMMON",
	"Black - Toothy": "BASE_COMMON",
	"Blue - Cigarette": "BASE_COMMON",
	"Blue - Cracked": "BASE_COMMON",
	"Blue - Default": "BASE_COMMON",
	"Blue - Fangs": "BASE_COMMON",
	"Blue - Gold Tooth": "BASE_COMMON",
	"Blue - Lockjaw": "BASE_COMMON",
	"Blue - Oooh": "BASE_COMMON",
	"Blue - Open": "BASE_COMMON",
	"Blue - Open-minded": "BASE_COMMON",
	"Blue - Sewn": "BASE_COMMON",
	"Blue - Side Open": "BASE_COMMON",
	"Blue - Toothy": "BASE_COMMON",
	"Gray - Cigarette": "BASE_COMMON",
	"Gray - Cracked": "BASE_COMMON",
	"Gray - Default": "BASE_COMMON",
	"Gray - Fangs": "BASE_COMMON",
	"Gray - Gold Tooth": "BASE_COMMON",
	"Gray - Lockjaw": "BASE_COMMON",
	"Gray - Oooh": "BASE_COMMON",
	"Gray - Open": "BASE_COMMON",
	"Gray - Open-minded": "BASE_COMMON",
	"Gray - Sewn": "BASE_COMMON",
	"Gray - Side Open": "BASE_COMMON",
	"Gray - Toothy": "BASE_COMMON",
	"Green - Cigarette": "BASE_COMMON",
	"Green - Cracked": "BASE_COMMON",
	"Green - Default": "BASE_COMMON",
	"Green - Fangs": "BASE_COMMON",
	"Green - Gold Tooth": "BASE_COMMON",
	"Green - Lockjaw": "BASE_COMMON",
	"Green - Oooh": "BASE_COMMON",
	"Green - Open": "BASE_COMMON",
	"Green - Open-minded": "BASE_COMMON",
	"Green - Sewn": "BASE_COMMON",
	"Green - Side Open": "BASE_COMMON",
	"Green - Toothy": "BASE_COMMON",
	"Purple - Cigarette": "BASE_COMMON",
	"Purple - Cracked": "BASE_COMMON",
	"Purple - Default": "BASE_COMMON",
	"Purple - Fangs": "BASE_COMMON",
	"Purple - Gold Tooth": "BASE_COMMON",
	"Purple - Lockjaw": "BASE_COMMON",
	"Purple - Oooh": "BASE_COMMON",
	"Purple - Open": "BASE_COMMON",
	"Purple - Open-minded": "BASE_COMMON",
	"Purple - Sewn": "BASE_COMMON",
	"Purple - Side Open": "BASE_COMMON",
	"Purple - Toothy": "BASE_COMMON",
	"Red - Cigarette": "BASE_COMMON",
	"Red - Cracked": "BASE_COMMON",
	"Red - Default": "BASE_COMMON",
	"Red - Fangs": "BASE_COMMON",
	"Red - Gold Tooth": "BASE_COMMON",
	"Red - Lockjaw": "BASE_COMMON",
	"Red - Oooh": "BASE_COMMON",
	"Red - Open": "BASE_COMMON",
	"Red - Open-minded": "BASE_COMMON",
	"Red - Sewn": "BASE_COMMON",
	"Red - Side Open": "BASE_COMMON",
	"Red - Toothy": "BASE_COMMON",
	"White - Cigarette": "BASE_COMMON",
	"White - Cracked": "BASE_COMMON",
	"White - Default": "BASE_COMMON",
	"White - Fangs": "BASE_COMMON",
	"White - Gold Tooth": "BASE_COMMON",
	"White - Lockjaw": "BASE_COMMON",
	"White - Oooh": "BASE_COMMON",
	"White - Open": "BASE_COMMON",
	"White - Open-minded": "BASE_COMMON",
	"White - Sewn": "BASE_COMMON",
	"White - Side Open": "BASE_COMMON",
	"White - Toothy": "BASE_COMMON",
	"Yellow - Cigarette": "BASE_COMMON",
	"Yellow - Cracked": "BASE_COMMON",
	"Yellow - Default": "BASE_COMMON",
	"Yellow - Fangs": "BASE_COMMON",
	"Yellow - Gold Tooth": "BASE_COMMON",
	"Yellow - Lockjaw": "BASE_COMMON",
	"Yellow - Oooh": "BASE_COMMON",
	"Yellow - Open": "BASE_COMMON",
	"Yellow - Open-minded": "BASE_COMMON",
	"Yellow - Sewn": "BASE_COMMON",
	"Yellow - Side Open": "BASE_COMMON",
	"Yellow - Toothy": "BASE_COMMON",

	"Aquarium - Default": "BASE_RARE",
	"Circuitry (Green) - Default": "BASE_RARE",
	"Diamond - Default": "BASE_RARE",
	"Emerald - Default": "BASE_RARE",
	"Galactite - Default": "BASE_RARE",
	"Glass - Default": "BASE_RARE",
	"Gold - Default": "BASE_RARE",
	"Golden Automaton - Default": "BASE_RARE",
	"Ice - Default": "BASE_RARE",
	"Infernal - Default": "BASE_RARE",
	"Liquid - Default": "BASE_RARE",
	"Robot - Default": "BASE_RARE",
	"Silver - Default": "BASE_RARE",
	"Slime - Default": "BASE_RARE",
	"Stone - Default": "BASE_RARE",
	"Terrarium - Default": "BASE_RARE",
	"Wooden - Default": "BASE_RARE",

	"Android - Default": "BASE_LEGENDARY",
	"Ape - Default": "BASE_LEGENDARY",
	"Candy Machine - Default": "BASE_LEGENDARY",
	"Circuitry (Purple) - Default": "BASE_LEGENDARY",
	"Cybernetic - Default": "BASE_LEGENDARY",
	"Diver - Default": "BASE_LEGENDARY",
	"Infernal (Blue) - Default": "BASE_LEGENDARY",
	"Lunar - Default": "BASE_LEGENDARY",
	"Mummy - Default": "BASE_LEGENDARY",
	"Mushroom - Default": "BASE_LEGENDARY",
	"Ornamental Automaton - Default": "BASE_LEGENDARY",
	"Pumpkinhead - Default": "BASE_LEGENDARY",
	"Purple Ooze - Default": "BASE_LEGENDARY",
	"Scarecrow - Default": "BASE_LEGENDARY",
	"Xenoid - Default": "BASE_LEGENDARY",

	"Balloon - Default": "BASE_MYTHIC",
	"Chicken - Default": "BASE_MYTHIC",
	"Infernal (Purple) - Default": "BASE_MYTHIC",
	"None": "BASE_MYTHIC",
	"Tiger - Default": "BASE_MYTHIC",

	"Ancient Cthulhu": "BASE_ANCIENT",
	"Ancient Default": "BASE_ANCIENT",
	"Ancient Open": "BASE_ANCIENT",
	"Ancient Squid": "BASE_ANCIENT",
	"Ancient Toothy Maw": "BASE_ANCIENT",

	"Ancient Cthulhu (Golden)": "BASE_GOLDEN_ANCIENT",
	"Ancient Default (Golden)": "BASE_GOLDEN_ANCIENT",
	"Ancient Open (Golden)": "BASE_GOLDEN_ANCIENT",
	"Ancient Squid (Golden)": "BASE_GOLDEN_ANCIENT",
	"Ancient Toothy Maw (Golden)": "BASE_GOLDEN_ANCIENT"
};