name: Dev CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Restart server application
        run: pm2 restart ETA
